name: Weekly Job Scraper

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs at 00:00 on Monday
  workflow_dispatch:  # Allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 reportlab aiohttp

    - name: Install DejaVu fonts
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-dejavu
        mkdir -p "Import Request/fonts"
        cp /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf "Import Request/fonts/"

    - name: Run scraper
      run: python "Import Request/import_requests.py"

    - name: Configure Git
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

    - name: Commit and push if there are changes
      run: |
        git add "Import Request/results/"
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update job listings $(date +'%Y-%m-%d')" && git push)

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: job-listings
        path: Import Request/results/*.pdf
