name: Weekly Job Scraper

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs at 00:00 on Monday
  workflow_dispatch:  # Allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 reportlab aiohttp

    - name: Install Arial font
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-liberation
        mkdir -p ~/.fonts
        cp /usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf ~/.fonts/arial.ttf
        fc-cache -f -v

    - name: Run scraper
      run: python "Import Request/import_requests.py"

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: job-listings
        path: Import Request/results/*.pdf
